### ISSUE TITLE
Horizontal Scrollbar in Chrome 34.0.1847.116

### ISSUE THREAD

**Issue by rhurling** [wycks/WordPress-Gear#63]
can be fixed by applying `box-sizing: border-box` to `header` element and `display: inline-block` to `#header-wrap`
but that moves the header elements to the left by 10-20px

**Comment by kim07** [comment]
:+1:

**Comment by franz-josef-kaiser** [comment]
As Chrome is a rolling release and there was neither a PR nor any other kind of update, I'm closing this one as too old.
