### ISSUE TITLE
WPX repository move

### ISSUE THREAD

**Issue by madvik** [wycks/WordPress-Gear#93]
The link to the repository WPX is dead.
WPX - Make it easier to use WordPress as a CMS

**Comment by alkah3st** [comment]
Hi, I am its creator. The repo was intentionally deleted because Advanced Custom Fields is far superior and I no longer support WPX.

**Comment by franz-josef-kaiser** [comment]
@madvik Would you mind filing a PR?

@alkah3st Thanks a bunch!

**Comment by madvik** [comment]
What is a PR ?
Thanks

**Comment by franz-josef-kaiser** [comment]
@madvik A _Pull Request_.

**Comment by madvik** [comment]
Sorry :-), it's done.

**Comment by franz-josef-kaiser** [comment]
@madvik This is pretty much the last open issue here for the _1.0.0 Milestone_. Would you mind linking to the PR? Couldn't find it. Thanks in advance!

**Comment by franz-josef-kaiser** [comment]
Link to WPX deleted. See explanation in #94
