### ISSUE TITLE
Add?

### ISSUE THREAD

**Issue by MikeNGarrett** [wycks/WordPress-Gear#95]
Seems relevant: http://wppb.io/

**Comment by franz-josef-kaiser** [comment]
@MikeNGarrett Please file a [Pull Request](https://github.com/wycks/WordPress-Gear/pulls). Also, please care to write meaningful subjects for both issues and Pull Requests as well as a summary of what the linked library, theme, framework, etc. is doing. Just 

> Add?

and _"Seems relevant"_ is too less to get something included in here. Please keep in mind that we are maintaining this in our free time and make it available for free. Thanks.

**Comment by MikeNGarrett** [comment]
Understood. I apologize for the brevity of my issue submission. I did not have the time myself to submit a formal pull request. I will endeavor to do so in the near future.

**Comment by franz-josef-kaiser** [comment]
np
